# Generated by Django 6.0.4 on 2026-04-16 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Liga",
                "verbose_name_plural": "Ligy",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.PositiveSmallIntegerField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Brankář"),
                            ("DF", "Obránce"),
                            ("MF", "Záložník"),
                            ("FW", "Útočník"),
                        ],
                        max_length=2,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Hráč",
                "verbose_name_plural": "Hráči",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
                ("start_year", models.PositiveIntegerField()),
                ("end_year", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Sezona",
                "verbose_name_plural": "Sezony",
                "ordering": ["-start_year", "-end_year"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="player_comments", to=settings.AUTH_USER_MODEL)),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="core.player")),
            ],
            options={
                "verbose_name": "Komentář",
                "verbose_name_plural": "Komentáře",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("stadium", models.CharField(max_length=100)),
                ("league", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teams", to="core.league")),
            ],
            options={
                "verbose_name": "Tým",
                "verbose_name_plural": "Týmy",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="players", to="core.team"),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("star_count", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="core.player")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="player_ratings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Hodnocení",
                "verbose_name_plural": "Hodnocení",
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("player", "user"), name="unique_player_rating_per_user")],
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("goals", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("yellow_cards", models.PositiveIntegerField(default=0)),
                ("red_cards", models.PositiveIntegerField(default=0)),
                ("appearances", models.PositiveIntegerField(default=0)),
                ("minutes_played", models.PositiveIntegerField(default=0)),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="core.player")),
                ("season", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="core.season")),
            ],
            options={
                "verbose_name": "Statistika",
                "verbose_name_plural": "Statistiky",
                "ordering": ["player__last_name", "-season__start_year"],
                "constraints": [models.UniqueConstraint(fields=("player", "season"), name="unique_player_statistic_per_season")],
            },
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(fields=("name", "league"), name="unique_team_name_per_league"),
        ),
    ]
